In [5]:
import numpy as np

In [6]:
my_list = [1,2,3]

In [7]:
ara = np.array(my_list)

In [8]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.arange(0,11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones(4)

array([1., 1., 1., 1.])

In [16]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.linspace(0,5,15)

array([0.        , 0.35714286, 0.71428571, 1.07142857, 1.42857143,
       1.78571429, 2.14285714, 2.5       , 2.85714286, 3.21428571,
       3.57142857, 3.92857143, 4.28571429, 4.64285714, 5.        ])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.random.rand(5)

array([0.47654134, 0.20560205, 0.85334127, 0.47487261, 0.74618327])

In [20]:
np.random.rand(5,3)

array([[0.01145213, 0.78285525, 0.31463753],
       [0.62169907, 0.47644804, 0.38940892],
       [0.15393097, 0.90019141, 0.91069345],
       [0.27033561, 0.20626053, 0.72864307],
       [0.7150777 , 0.7321415 , 0.38782585]])

In [21]:
np.random.randn(3,5)

array([[ 1.4684059 , -0.12753212,  0.35294671,  1.61484628, -0.08252147],
       [-0.56199437,  0.0601844 , -0.97043912, -0.49097951, -0.43639928],
       [-1.19481071,  0.70247985,  0.19606236,  0.73848629, -1.15116312]])

In [22]:
np.random.randint(1,100)

91

In [23]:
np.random.randint(1,100,10)

array([91, 59, 54, 68, 92, 44, 14, 49, 15, 35])

In [24]:
arr = np.arange(25)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
ranarr = np.random.randint(0,50,10)

In [27]:
ranarr

array([32, 28, 24,  3, 11, 41,  1, 13,  2,  7])

In [28]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
ranarr.max()

41

In [30]:
ranarr.min()

1

In [31]:
ranarr.argmax()

5

In [32]:
ranarr.argmin()

6

In [33]:
arr.shape

(25,)

In [34]:
arr = arr.reshape(5,5)

In [35]:
arr.shape

(5, 5)

In [36]:
arr.dtype

dtype('int32')

In [37]:
array1 = np.arange(1,11)
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
array1[:2]

array([1, 2])

In [39]:
array1_copy = array1.copy()
array1_copy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
array1_copy[:] = 100
array1_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [41]:
array1_copy[:3] = 111
array1_copy

array([111, 111, 111, 100, 100, 100, 100, 100, 100, 100])

In [42]:
matrix = np.array([[5,10,15], [20,25,30], [35,40,45]])
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [43]:
matrix[0][1]

10

In [44]:
matrix[0]

array([ 5, 10, 15])

In [45]:
matrix[0,1]

10

In [46]:
matrix[:2,1:]

array([[10, 15],
       [25, 30]])

In [47]:
matrix[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [48]:
array2 = np.arange(1,11)
array2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [104]:
bool_array2 = array2 > 5
bool_array2

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [106]:
array2[bool_array2]

array([ 6,  7,  8,  9, 10])

In [108]:
array2[array2 > 5]

array([ 6,  7,  8,  9, 10])

In [131]:
matrix2 = np.arange(50).reshape(5,10)
matrix2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [138]:
matrix2[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [140]:
# NumPy Operations

In [159]:
array3 = np.arange(0,11)
array3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [163]:
array3 + array3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [165]:
array3 * array3

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [169]:
array3 - array3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [173]:
array3 / array3

C:\Users\Fer\AppData\Local\Temp\ipykernel_17812\2920792227.py:1: RuntimeWarning: invalid value encountered in divide
  array3 / array3


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [175]:
1 / array3

C:\Users\Fer\AppData\Local\Temp\ipykernel_17812\228780447.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / array3


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [177]:
array3 ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [179]:
np.sqrt(array3)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [181]:
np.exp(array3)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [183]:
np.max(array3)

10

In [187]:
np.sin(array3)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [191]:
np.log(array3)

C:\Users\Fer\AppData\Local\Temp\ipykernel_17812\2630074268.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(array3)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])